
// This file contains temporary demo data for development purposes.
// It is not connected to the live application state or Firebase.
// You can safely delete this file when you are using real data.

export const demoProjects = [
    {
        id: 'proj_1',
        name: 'Modern Villa at Bashundhara',
        clientName: 'Rezaul Karim',
        location: 'Bashundhara R/A, Dhaka',
        budget: 15000000,
        status: 'Ongoing',
        startDate: '2025-11-01',
        endDate: '2026-06-30',
        createdAt: { seconds: 1672531200, nanoseconds: 0 },
        tasks: [
            { id: 't1-1', name: 'Foundation and Piling', status: 'Completed', priority: 'High' },
            { id: 't1-2', name: 'Ground Floor Structure', status: 'Completed', priority: 'High' },
            { id: 't1-3', name: '1st Floor Slab Casting', status: 'In Progress', priority: 'High' },
            { id: 't1-4', name: 'Brickwork and Walls', status: 'Not Started', priority: 'Medium' },
            { id: 't1-5', name: 'Electrical & Plumbing Rough-in', status: 'Not Started', priority: 'Medium' },
        ],
        milestones: [
            { id: 'm1-1', name: 'Structural Completion', deadline: '2026-03-15', completed: false },
            { id: 'm1-2', name: 'Handover', deadline: '2026-06-30', completed: false },
        ]
    },
    {
        id: 'proj_2',
        name: 'Commercial Tower in Gulshan',
        clientName: 'Farida Khanam',
        location: 'Gulshan-2, Dhaka',
        budget: 75000000,
        status: 'Planned',
        startDate: '2026-02-01',
        endDate: '2027-08-31',
        createdAt: { seconds: 1675209600, nanoseconds: 0 },
        tasks: [
            { id: 't2-1', name: 'Excavation and Soil Test', status: 'Not Started', priority: 'High' },
            { id: 't2-2', name: 'Basement Construction', status: 'Not Started', priority: 'High' },
        ],
        milestones: [
            { id: 'm2-1', name: 'Project Kick-off', deadline: '2026-02-01', completed: true },
            { id: 'm2-2', name: 'Substructure Completion', deadline: '2026-08-01', completed: false },
        ]
    },
    {
        id: 'proj_3',
        name: 'Duplex House Renovation',
        clientName: 'Anis Ahmed',
        location: 'Dhanmondi, Dhaka',
        budget: 5000000,
        status: 'Completed',
        startDate: '2025-09-01',
        endDate: '2026-01-15',
        createdAt: { seconds: 1669852800, nanoseconds: 0 },
        tasks: [
            { id: 't3-1', name: 'Demolition and Cleanup', status: 'Completed', priority: 'High' },
            { id: 't3-2', name: 'Structural Repair', status: 'Completed', priority: 'Medium' },
            { id: 't3-3', name: 'Interior Finishing', status: 'Completed', priority: 'High' },
            { id: 't3-4', name: 'Painting and Final Touches', status: 'Completed', priority: 'Low' },
        ],
        milestones: [
            { id: 'm3-1', name: 'Project Completion', deadline: '2026-01-15', completed: true },
        ]
    },
    {
        id: 'proj_4',
        name: 'Factory Shed at Savar',
        clientName: 'Spectra Group',
        location: 'EPZ, Savar',
        budget: 25000000,
        status: 'Ongoing',
        startDate: '2025-12-01',
        endDate: '2026-05-31',
        createdAt: { seconds: 1678838400, nanoseconds: 0 },
        tasks: [
            { id: 't4-1', name: 'Site Leveling', status: 'Completed', priority: 'High' },
            { id: 't4-2', name: 'Steel Structure Erection', status: 'Completed', priority: 'High' },
            { id: 't4-3', name: 'Roofing and Cladding', status: 'In Progress', priority: 'Medium' },
            { id: 't4-4', name: 'MEP Installation', status: 'Blocked', priority: 'High' },
        ],
        milestones: [
            { id: 'm4-1', name: 'Structure Ready', deadline: '2026-02-28', completed: false },
            { id: 'm4-2', name: 'Ready for Machinery', deadline: '2026-05-31', completed: false },
        ]
    },
    {
        id: 'proj_5',
        name: 'Interior Design for Office',
        clientName: 'Creative Solutions Ltd.',
        location: 'Banani, Dhaka',
        budget: 2500000,
        status: 'On Hold',
        startDate: '2026-01-10',
        endDate: '2026-03-10',
        createdAt: { seconds: 1680307200, nanoseconds: 0 },
        tasks: [],
        milestones: []
    },
    {
        id: 'proj_6',
        name: 'Luxury Apartment Complex',
        clientName: 'Urban Properties',
        location: 'Uttara, Dhaka',
        budget: 120000000,
        status: 'Ongoing',
        startDate: '2025-07-01',
        endDate: '2027-12-31',
        createdAt: { seconds: 1682985600, nanoseconds: 0 },
        tasks: [
            { id: 't6-1', name: 'Piling Works', status: 'Completed', priority: 'High' },
            { id: 't6-2', name: 'Foundation Works', status: 'Completed', priority: 'High' },
            { id: 't6-3', name: 'Casting up to 5th Floor', status: 'Completed', priority: 'Medium' },
            { id: 't6-4', name: 'Casting up to 10th Floor', status: 'In Progress', priority: 'Medium' },
        ],
        milestones: [
            { id: 'm6-1', name: 'Superstructure Complete', deadline: '2026-12-31', completed: false },
            { id: 'm6-2', name: 'Project Handover', deadline: '2027-12-31', completed: false },
        ]
    },
    {
        id: 'proj_8',
        name: 'Private Resort at Gazipur',
        clientName: 'Nadia Rahman',
        location: 'Gazipur, Dhaka',
        budget: 55000000,
        status: 'Ongoing',
        startDate: '2025-10-01',
        endDate: '2026-10-30',
        createdAt: { seconds: 1688169600, nanoseconds: 0 },
        tasks: [
            { id: 't8-1', name: 'Landscaping', status: 'Completed', priority: 'Medium' },
            { id: 't8-2', name: 'Cottage Construction', status: 'Completed', priority: 'High' },
            { id: 't8-3', name: 'Swimming Pool', status: 'In Progress', priority: 'High' },
            { id: 't8-4', name: 'Interior Decoration', status: 'Not Started', priority: 'Medium' },
        ],
        milestones: [
            { id: 'm8-1', 'name': 'Phase 1 Complete', deadline: '2026-04-30', completed: false },
        ]
    }
];

export const demoClients = [
    {
        id: 'client_1',
        name: 'Rezaul Karim',
        phone: '01711-xxxxxx',
        address: 'House 12, Road 5, Bashundhara R/A',
        createdAt: { seconds: 1672531100, nanoseconds: 0 },
    },
    {
        id: 'client_2',
        name: 'Farida Khanam',
        phone: '01912-xxxxxx',
        address: 'Plot 21, Gulshan Avenue, Gulshan-2',
        createdAt: { seconds: 1675209500, nanoseconds: 0 },
    },
    {
        id: 'client_3',
        name: 'Anis Ahmed',
        phone: '01815-xxxxxx',
        address: 'Road 7/A, Dhanmondi',
        createdAt: { seconds: 1669852700, nanoseconds: 0 },
    },
    {
        id: 'client_4',
        name: 'Spectra Group',
        phone: '01713-xxxxxx',
        address: 'Savar EPZ, Dhaka',
        createdAt: { seconds: 1678838300, nanoseconds: 0 },
    },
    {
        id: 'client_5',
        name: 'Creative Solutions Ltd.',
        phone: '01678-xxxxxx',
        address: 'Road 11, Banani, Dhaka',
        createdAt: { seconds: 1680307100, nanoseconds: 0 },
    },
    {
        id: 'client_6',
        name: 'Urban Properties',
        phone: '01551-xxxxxx',
        address: 'Sector 4, Uttara, Dhaka',
        createdAt: { seconds: 1682985500, nanoseconds: 0 },
    },
    {
        id: 'client_7',
        name: 'Maple Leaf International',
        phone: '01990-xxxxxx',
        address: 'Mirpur-10, Dhaka',
        createdAt: { seconds: 1685577500, nanoseconds: 0 },
    },
    {
        id: 'client_8',
        name: 'Nadia Rahman',
        phone: '01888-xxxxxx',
        address: 'Gazipur Sadar, Gazipur',
        createdAt: { seconds: 1688169500, nanoseconds: 0 },
    },
    {
        id: 'client_9',
        name: 'Govt. Project (RHD)',
        phone: 'N/A',
        address: 'Dhaka Division',
        createdAt: { seconds: 1677628700, nanoseconds: 0 },
    }
];

export const demoEmployees = [
    {
        id: 'emp_1',
        name: 'Jamal Uddin',
        role: 'Site Engineer',
        phone: '01722-xxxxxx',
        currentProject: 'Modern Villa at Bashundhara',
        status: 'Active',
        totalPaid: 250000,
        imageUrl: 'https://picsum.photos/seed/Jamal%20Uddin/200/200',
        createdAt: { seconds: 1672617600, nanoseconds: 0 },
    },
    {
        id: 'emp_2',
        name: 'Solaiman',
        role: 'Mason (Rajmistri)',
        phone: '01688-xxxxxx',
        currentProject: 'Modern Villa at Bashundhara',
        status: 'Active',
        totalPaid: 120000,
        imageUrl: 'https://picsum.photos/seed/Solaiman/200/200',
        createdAt: { seconds: 1672704000, nanoseconds: 0 },
    },
    {
        id: 'emp_3',
        name: 'Afzal Hossain',
        role: 'Project Manager',
        phone: '01555-xxxxxx',
        currentProject: 'Luxury Apartment Complex',
        status: 'Active',
        totalPaid: 450000,
        imageUrl: 'https://picsum.photos/seed/Afzal%20Hossain/200/200',
        createdAt: { seconds: 1669939200, nanoseconds: 0 },
    },
    {
        id: 'emp_4',
        name: 'Rafiqul Islam',
        role: 'Electrician',
        phone: '01999-xxxxxx',
        currentProject: 'Factory Shed at Savar',
        status: 'Active',
        totalPaid: 95000,
        imageUrl: 'https://picsum.photos/seed/Rafiqul%20Islam/200/200',
        createdAt: { seconds: 1678924800, nanoseconds: 0 },
    },
    {
        id: 'emp_5',
        name: 'Harun',
        role: 'Labor (Jogali)',
        phone: '01333-xxxxxx',
        currentProject: 'Factory Shed at Savar',
        status: 'On Leave',
        totalPaid: 45000,
        imageUrl: 'https://picsum.photos/seed/Harun/200/200',
        createdAt: { seconds: 1678924800, nanoseconds: 0 },
    },
    {
        id: 'emp_6',
        name: 'Babul Ahmed',
        role: 'Painter',
        phone: '01821-xxxxxx',
        currentProject: 'Duplex House Renovation',
        status: 'Inactive',
        totalPaid: 150000,
        imageUrl: 'https://picsum.photos/seed/Babul%20Ahmed/200/200',
        createdAt: { seconds: 1670025600, nanoseconds: 0 },
    },
    {
        id: 'emp_7',
        name: 'Kamrul Hasan',
        role: 'Foreman',
        phone: '01715-xxxxxx',
        currentProject: 'Luxury Apartment Complex',
        status: 'Active',
        totalPaid: 180000,
        imageUrl: 'https://picsum.photos/seed/Kamrul%20Hasan/200/200',
        createdAt: { seconds: 1683072000, nanoseconds: 0 },
    },
    {
        id: 'emp_8',
        name: 'Ratan Mia',
        role: 'Rod Mistri',
        phone: '01623-xxxxxx',
        currentProject: 'Luxury Apartment Complex',
        status: 'Active',
        totalPaid: 110000,
        imageUrl: 'https://picsum.photos/seed/Ratan%20Mia/200/200',
        createdAt: { seconds: 1683158400, nanoseconds: 0 },
    },
    {
        id: 'emp_9',
        name: 'Firoz Khan',
        role: 'Plumber',
        phone: '01918-xxxxxx',
        currentProject: 'Modern Villa at Bashundhara',
        status: 'Active',
        totalPaid: 85000,
        imageUrl: 'https://picsum.photos/seed/Firoz%20Khan/200/200',
        createdAt: { seconds: 1673827200, nanoseconds: 0 },
    },
    {
        id: 'emp_10',
        name: 'Shahidul Alam',
        role: 'Tiles Mistri',
        phone: '01845-xxxxxx',
        currentProject: '',
        status: 'Active',
        totalPaid: 92000,
        imageUrl: 'https://picsum.photos/seed/Shahidul%20Alam/200/200',
        createdAt: { seconds: 1674864000, nanoseconds: 0 },
    },
    {
        id: 'emp_11',
        name: 'Alamgir Kabir',
        role: 'Security Guard',
        phone: '01311-xxxxxx',
        currentProject: 'Factory Shed at Savar',
        status: 'Active',
        totalPaid: 65000,
        imageUrl: 'https://picsum.photos/seed/Alamgir%20Kabir/200/200',
        createdAt: { seconds: 1678838400, nanoseconds: 0 },
    },
     {
        id: 'emp_12',
        name: 'Mizanur Rahman',
        role: 'Site Engineer',
        phone: '01723-xxxxxx',
        currentProject: 'Private Resort at Gazipur',
        status: 'Active',
        totalPaid: 230000,
        imageUrl: 'https://picsum.photos/seed/Mizanur%20Rahman/200/200',
        createdAt: { seconds: 1688256000, nanoseconds: 0 },
    },
    {
        id: 'emp_13',
        name: 'Kader',
        role: 'Mason (Rajmistri)',
        phone: '01689-xxxxxx',
        currentProject: 'Private Resort at Gazipur',
        status: 'Active',
        totalPaid: 115000,
        imageUrl: 'https://picsum.photos/seed/Kader/200/200',
        createdAt: { seconds: 1688342400, nanoseconds: 0 },
    }
];

export const demoTransactions = [
    // December 2025
    { id: 'tran_1', description: 'Payment from Rezaul Karim', amount: 2500000, type: 'income', category: 'payment', date: '2025-12-15', projectId: 'proj_1', paymentMethod: 'Bank Transfer', reference: 'TR-58290', createdAt: { seconds: 1734204000 } },
    { id: 'tran_2', description: 'Purchase of 200 bags of cement', amount: 110000, type: 'expense', category: 'materials', date: '2025-12-16', projectId: 'proj_1', paymentMethod: 'Cash', reference: 'RCPT-1020', createdAt: { seconds: 1734290400 } },
    { id: 'tran_3', description: 'Labor wages for Bashundhara site', amount: 75000, type: 'expense', category: 'labor', date: '2025-12-17', projectId: 'proj_1', paymentMethod: 'Cash', reference: '', createdAt: { seconds: 1734376800 } },
    { id: 'tran_4', description: 'Final payment from Anis Ahmed', amount: 1500000, type: 'income', category: 'payment', date: '2025-12-18', projectId: 'proj_3', paymentMethod: 'Check', reference: 'CHK-9910', createdAt: { seconds: 1734463200 } },
    { id: 'tran_5', description: 'Initial payment for Gulshan Tower', amount: 15000000, type: 'income', category: 'payment', date: '2025-12-19', projectId: 'proj_2', paymentMethod: 'Bank Transfer', reference: 'TR-60145', createdAt: { seconds: 1734549600 } },
    { id: 'tran_6', description: 'Steel purchase (5 tons) for Savar', amount: 450000, type: 'expense', category: 'materials', date: '2025-12-20', projectId: 'proj_4', paymentMethod: 'Check', reference: 'CHK-9980', createdAt: { seconds: 1734636000 } },
    { id: 'tran_7', description: 'Office rent - December 2025', amount: 50000, type: 'expense', category: 'overhead', date: '2025-12-21', projectId: '', paymentMethod: 'Cash', reference: '', createdAt: { seconds: 1734722400 } },
    { id: 'tran_8', description: 'Payment for Interior Design', amount: 1000000, type: 'income', category: 'payment', date: '2025-12-22', projectId: 'proj_5', paymentMethod: 'Bank Transfer', reference: 'TR-59000', createdAt: { seconds: 1734808800 } },
    { id: 'tran_9', description: 'Salary to Jamal Uddin (Dec)', amount: 50000, type: 'expense', category: 'labor', date: '2025-12-23', projectId: 'proj_1', employeeId: 'emp_1', paymentMethod: 'Bank Transfer', reference: '', createdAt: { seconds: 1734895200 } },
    { id: 'tran_10', description: 'Excavator rental for Savar site', amount: 120000, type: 'expense', category: 'equipment', date: '2025-12-24', projectId: 'proj_4', paymentMethod: 'Cash', reference: 'R-400', createdAt: { seconds: 1734981600 } },
    { id: 'tran_11', description: '1st installment from Urban Properties', amount: 12000000, type: 'income', category: 'payment', date: '2025-12-25', projectId: 'proj_6', paymentMethod: 'Bank Transfer', reference: 'TR-62100', createdAt: { seconds: 1735068000 } },
    { id: 'tran_12', description: 'Piling work for Uttara', amount: 750000, type: 'expense', category: 'materials', date: '2025-12-26', projectId: 'proj_6', paymentMethod: 'Check', reference: 'CHK-10010', createdAt: { seconds: 1735154400 } },
    { id: 'tran_13', description: 'Salary to Afzal Hossain (Dec)', amount: 80000, type: 'expense', category: 'labor', date: '2025-12-27', projectId: 'proj_6', employeeId: 'emp_3', paymentMethod: 'Bank Transfer', reference: '', createdAt: { seconds: 1735240800 } },
    { id: 'tran_14', description: 'Bricks and sand for Gazipur', amount: 150000, type: 'expense', category: 'materials', date: '2025-12-28', projectId: 'proj_8', paymentMethod: 'Cash', reference: 'RCPT-2100', createdAt: { seconds: 1735327200 } },
    { id: 'tran_15', description: '1st installment from Nadia Rahman', amount: 5000000, type: 'income', category: 'payment', date: '2025-12-29', projectId: 'proj_8', paymentMethod: 'Bank Transfer', reference: 'TR-63550', createdAt: { seconds: 1735413600 } },
    { id: 'tran_16', description: 'Utility Bills for Head Office (Dec)', amount: 25000, type: 'expense', category: 'overhead', date: '2025-12-30', projectId: '', paymentMethod: 'Mobile Money', reference: '', createdAt: { seconds: 1735500000 } },
    { id: 'tran_17', description: 'Transportation to Gazipur site', amount: 75000, type: 'expense', category: 'transport', date: '2025-12-31', projectId: 'proj_8', paymentMethod: 'Cash', reference: '', createdAt: { seconds: 1735586400 } },
    // January 2026
    { id: 'tran_18', description: 'New Year Bonus for Staff', amount: 150000, type: 'expense', category: 'overhead', date: '2026-01-01', projectId: '', paymentMethod: 'Cash', reference: '', createdAt: { seconds: 1735672800 } },
    { id: 'tran_19', description: '2nd installment for Bashundhara Villa', amount: 3000000, type: 'income', category: 'payment', date: '2026-01-02', projectId: 'proj_1', paymentMethod: 'Bank Transfer', reference: 'TR-58292', createdAt: { seconds: 1735759200 } },
    { id: 'tran_20', description: 'Purchase of electrical wires', amount: 220000, type: 'expense', category: 'materials', date: '2026-01-03', projectId: 'proj_1', paymentMethod: 'Cash', reference: 'RCPT-1024', createdAt: { seconds: 1735845600 } },
    { id: 'tran_21', description: 'Weekly labor wages (Savar)', amount: 115000, type: 'expense', category: 'labor', date: '2026-01-04', projectId: 'proj_4', paymentMethod: 'Cash', reference: '', createdAt: { seconds: 1735932000 } },
    { id: 'tran_22', description: 'Advance payment for school extension', amount: 8000000, type: 'income', category: 'payment', date: '2026-01-05', projectId: 'proj_7', paymentMethod: 'Check', reference: 'CHK-10050', createdAt: { seconds: 1736018400 } },
    { id: 'tran_23', description: 'Safety equipment purchase', amount: 95000, type: 'expense', category: 'overhead', date: '2026-01-06', projectId: '', paymentMethod: 'Cash', reference: 'RCPT-1025', createdAt: { seconds: 1736104800 } },
    { id: 'tran_24', description: 'Plumbing materials for Villa', amount: 180000, type: 'expense', category: 'materials', date: '2026-01-07', projectId: 'proj_1', paymentMethod: 'Check', reference: 'CHK-9985', createdAt: { seconds: 1736191200 } },
    { id: 'tran_25', description: 'Payment from Spectra Group (2nd)', amount: 5000000, type: 'income', category: 'payment', date: '2026-01-08', projectId: 'proj_4', paymentMethod: 'Bank Transfer', reference: 'TR-60150', createdAt: { seconds: 1736277600 } },
    { id: 'tran_26', description: 'Diesel for generator', amount: 15000, type: 'expense', category: 'equipment', date: '2026-01-09', projectId: 'proj_4', paymentMethod: 'Cash', reference: '', createdAt: { seconds: 1736364000 } },
    { id: 'tran_27', description: 'Salary payment to Mizanur Rahman', amount: 60000, type: 'expense', category: 'labor', date: '2026-01-10', projectId: 'proj_8', employeeId: 'emp_12', paymentMethod: 'Bank Transfer', reference: '', createdAt: { seconds: 1736450400 } },
    { id: 'tran_28', description: 'Architectural drawing fees', amount: 250000, type: 'expense', category: 'overhead', date: '2026-01-11', projectId: 'proj_2', paymentMethod: 'Check', reference: 'CHK-10015', createdAt: { seconds: 1736536800 } },
    { id: 'tran_29', description: 'Final bill from Govt. Project', amount: 4500000, type: 'income', category: 'payment', date: '2026-01-12', projectId: 'proj_9', paymentMethod: 'Bank Transfer', reference: 'TR-64000', createdAt: { seconds: 1736623200 } },
    { id: 'tran_30', description: 'Catering for client meeting', amount: 12000, type: 'expense', category: 'overhead', date: '2026-01-13', projectId: '', paymentMethod: 'Mobile Money', reference: '', createdAt: { seconds: 1736709600 } }
];

export const demoAttendance = [
    { id: 'att_1', employeeId: 'emp_2', projectId: 'proj_1', date: '2026-01-13', checkIn: '08:05', checkOut: '17:03', status: 'Present', overtime: 1 },
    { id: 'att_2', employeeId: 'emp_4', projectId: 'proj_4', date: '2026-01-13', checkIn: '08:00', checkOut: '17:00', status: 'Present', overtime: 0 },
    { id: 'att_3', employeeId: 'emp_5', projectId: 'proj_4', date: '2026-01-13', checkIn: null, checkOut: null, status: 'Absent', overtime: 0 },
    { id: 'att_4', employeeId: 'emp_7', projectId: 'proj_6', date: '2026-01-13', checkIn: '09:30', checkOut: '18:00', status: 'Late', overtime: 0 },
    { id: 'att_5', employeeId: 'emp_8', projectId: 'proj_6', date: '2026-01-13', checkIn: '08:00', checkOut: '13:00', status: 'Half-day', overtime: 0 },
];

export const demoEquipment = [
    { id: 'eq_1', name: 'Concrete Mixer', category: 'Heavy', ownership: 'Owned', status: 'In Use', projectId: 'proj_1', lastService: '2025-12-01', nextService: '2026-03-01' },
    { id: 'eq_2', name: 'Tower Crane', category: 'Heavy', ownership: 'Rented', status: 'In Use', projectId: 'proj_6', lastService: '2025-11-15', nextService: '2026-02-15' },
    { id: 'eq_3', name: 'Excavator', category: 'Heavy', ownership: 'Rented', status: 'Idle', projectId: null, lastService: '2026-01-05', nextService: '2026-04-05' },
    { id: 'eq_4', name: 'Power Drill (x5)', category: 'Light', ownership: 'Owned', status: 'In Use', projectId: 'proj_1', lastService: 'N/A', nextService: 'N/A' },
    { id: 'eq_5', name: 'Generator 5kW', category: 'Light', ownership: 'Owned', status: 'Maintenance', projectId: null, lastService: '2025-10-10', nextService: '2026-01-10' },
];

export const demoMaterials = [
    { id: 'mat_1', name: 'Portland Cement', unit: 'Bags', currentStock: 450, reorderLevel: 100, lastUpdated: '2026-01-10' },
    { id: 'mat_2', name: 'Deformed Steel Rod (16mm)', unit: 'Tons', currentStock: 12.5, reorderLevel: 5, lastUpdated: '2026-01-08' },
    { id: 'mat_3', name: 'Sylhet Sand', unit: 'cft', currentStock: 850, reorderLevel: 500, lastUpdated: '2026-01-11' },
    { id: 'mat_4', name: '1st Class Bricks', unit: 'Pieces', currentStock: 8500, reorderLevel: 10000, lastUpdated: '2026-01-09' },
    { id: 'mat_5', name: 'Stone Chips (3/4")', unit: 'cft', currentStock: 350, reorderLevel: 200, lastUpdated: '2026-01-12' },
];
